apiVersion: v1
kind: Service
metadata:
  name: devops-lab
  namespace: devops-lab
  labels:
    app: devops-lab
spec:
  type: NodePort
  selector:
    app: devops-lab
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080   # Access at http://<pi-ip>:30080
